"""
parse_chatgpt.py
----------------
Parses your ChatGPT conversations.json export and extracts
cybersecurity-relevant exchanges into a knowledge_base.txt file
for use in your CyberGuard AI system prompt.

Usage:
    python scripts/parse_chatgpt.py --input conversations.json --output knowledge_base.txt
"""

import json
import argparse
from pathlib import Path

CYBER_KEYWORDS = [
    "kql", "sentinel", "defender", "splunk", "siem",
    "cve", "cvss", "vulnerability", "patch", "exploit",
    "mitre", "att&ck", "threat", "hunt", "ioc", "ioa",
    "risk", "assessment", "nist", "iso 27001", "cis control",
    "incident", "malware", "ransomware", "phishing", "lateral",
    "privilege", "escalation", "persistence", "exfiltration",
    "firewall", "endpoint", "edr", "xdr", "soc", "triage",
    "playbook", "runbook", "governance", "compliance", "audit",
    "pentest", "red team", "blue team", "detection", "sigma"
]

def is_relevant(text: str) -> bool:
    lower = text.lower()
    return any(kw in lower for kw in CYBER_KEYWORDS)

def extract_text(content) -> str:
    if isinstance(content, str):
        return content
    if isinstance(content, dict):
        parts = content.get("parts", [])
        return " ".join(str(p) for p in parts if isinstance(p, str))
    if isinstance(content, list):
        return " ".join(str(p) for p in content if isinstance(p, str))
    return ""

def parse_conversations(input_path: str, output_path: str):
    with open(input_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    chunks = []
    total = 0
    kept = 0

    for convo in data:
        title = convo.get("title", "Untitled")
        mapping = convo.get("mapping", {})

        pairs = []
        user_msg = None

        # Walk nodes in order
        nodes = list(mapping.values())
        nodes.sort(key=lambda n: n.get("message", {}).get("create_time") or 0 if n.get("message") else 0)

        for node in nodes:
            msg = node.get("message")
            if not msg:
                continue
            role = msg.get("author", {}).get("role")
            content = msg.get("content", {})
            text = extract_text(content).strip()
            if not text:
                continue
            total += 1

            if role == "user":
                user_msg = text
            elif role == "assistant" and user_msg:
                combined = user_msg + " " + text
                if is_relevant(combined):
                    pairs.append((user_msg, text))
                    kept += 1
                user_msg = None

        if pairs:
            chunk = f"## Conversation: {title}\n\n"
            for u, a in pairs:
                chunk += f"**Analyst:** {u}\n\n**Assistant:** {a}\n\n---\n\n"
            chunks.append(chunk)

    output = f"""# CyberGuard AI Knowledge Base
# Extracted from ChatGPT export
# Total messages scanned: {total} | Relevant exchanges kept: {kept}
# Generated by parse_chatgpt.py
# -----------------------------------------------
# Paste relevant sections into your system prompt
# -----------------------------------------------

"""
    output += "\n\n".join(chunks)

    Path(output_path).write_text(output, encoding="utf-8")
    print(f"Done. Scanned {total} messages, kept {kept} relevant exchanges.")
    print(f"Output written to: {output_path}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Parse ChatGPT export for CyberGuard AI")
    parser.add_argument("--input", default="conversations.json", help="Path to conversations.json")
    parser.add_argument("--output", default="knowledge_base.txt", help="Output file path")
    args = parser.parse_args()
    parse_conversations(args.input, args.output)
